version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./package.json
          acition: rebuild
        - path: ./next.config.js
          acition: rebuild
        - path: ./package-lock.json
          acition: rebuild
        - path: .
          target: /app
          acition: sync
    environment:
      - DB_URL=mongodb+srv://sujata:rnZzJjIDr3bIDymV@cluster0.hnn88vs.mongodb.net/ 
volumes:
  tasked: