version: '3'

services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js