version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=4000